#include <array>
#include <cstdint>
#include <cstdlib>
#include <iostream>
#include <string>

#include <pyc/cpp/pyc_tb.hpp>

// Generated by `pyc-compile --emit=cpp`.
#include "janus_tmu_pyc_gen.hpp"

using pyc::cpp::Testbench;
using pyc::cpp::Wire;

namespace {

constexpr int kNodes = 8;
constexpr int kWords = 32; // 256B / 8B

using W1 = Wire<1>;
using W8 = Wire<8>;
using W20 = Wire<20>;
using W64 = Wire<64>;

using DataWords = std::array<std::uint64_t, kWords>;

struct Ifaces {
  std::array<W1 *, kNodes> req_valid;
  std::array<W1 *, kNodes> req_ready;
  std::array<W1 *, kNodes> req_write;
  std::array<W20 *, kNodes> req_addr;
  std::array<std::array<W64 *, kWords>, kNodes> req_wdata;
  std::array<std::array<W8 *, kWords>, kNodes> req_wstrb;
  std::array<W20 *, kNodes> req_tag;

  std::array<W1 *, kNodes> rsp_valid;
  std::array<W1 *, kNodes> rsp_ready;
  std::array<std::array<W64 *, kWords>, kNodes> rsp_rdata;
  std::array<W20 *, kNodes> rsp_tag;
};

static Ifaces make_ifaces(pyc::gen::janus_tmu_pyc &dut) {
  Ifaces io{};
  io.req_valid = {&dut.n0_req_valid, &dut.n1_req_valid, &dut.n2_req_valid, &dut.n3_req_valid,
                  &dut.n4_req_valid, &dut.n5_req_valid, &dut.n6_req_valid, &dut.n7_req_valid};
  io.req_ready = {&dut.n0_req_ready, &dut.n1_req_ready, &dut.n2_req_ready, &dut.n3_req_ready,
                  &dut.n4_req_ready, &dut.n5_req_ready, &dut.n6_req_ready, &dut.n7_req_ready};
  io.req_write = {&dut.n0_req_write, &dut.n1_req_write, &dut.n2_req_write, &dut.n3_req_write,
                  &dut.n4_req_write, &dut.n5_req_write, &dut.n6_req_write, &dut.n7_req_write};
  io.req_addr = {&dut.n0_req_addr, &dut.n1_req_addr, &dut.n2_req_addr, &dut.n3_req_addr,
                 &dut.n4_req_addr, &dut.n5_req_addr, &dut.n6_req_addr, &dut.n7_req_addr};
  io.req_wdata = {{
    {&dut.n0_req_wdata_w0, &dut.n0_req_wdata_w1, &dut.n0_req_wdata_w2, &dut.n0_req_wdata_w3, &dut.n0_req_wdata_w4, &dut.n0_req_wdata_w5, &dut.n0_req_wdata_w6, &dut.n0_req_wdata_w7, &dut.n0_req_wdata_w8, &dut.n0_req_wdata_w9, &dut.n0_req_wdata_w10, &dut.n0_req_wdata_w11, &dut.n0_req_wdata_w12, &dut.n0_req_wdata_w13, &dut.n0_req_wdata_w14, &dut.n0_req_wdata_w15, &dut.n0_req_wdata_w16, &dut.n0_req_wdata_w17, &dut.n0_req_wdata_w18, &dut.n0_req_wdata_w19, &dut.n0_req_wdata_w20, &dut.n0_req_wdata_w21, &dut.n0_req_wdata_w22, &dut.n0_req_wdata_w23, &dut.n0_req_wdata_w24, &dut.n0_req_wdata_w25, &dut.n0_req_wdata_w26, &dut.n0_req_wdata_w27, &dut.n0_req_wdata_w28, &dut.n0_req_wdata_w29, &dut.n0_req_wdata_w30, &dut.n0_req_wdata_w31},
    {&dut.n1_req_wdata_w0, &dut.n1_req_wdata_w1, &dut.n1_req_wdata_w2, &dut.n1_req_wdata_w3, &dut.n1_req_wdata_w4, &dut.n1_req_wdata_w5, &dut.n1_req_wdata_w6, &dut.n1_req_wdata_w7, &dut.n1_req_wdata_w8, &dut.n1_req_wdata_w9, &dut.n1_req_wdata_w10, &dut.n1_req_wdata_w11, &dut.n1_req_wdata_w12, &dut.n1_req_wdata_w13, &dut.n1_req_wdata_w14, &dut.n1_req_wdata_w15, &dut.n1_req_wdata_w16, &dut.n1_req_wdata_w17, &dut.n1_req_wdata_w18, &dut.n1_req_wdata_w19, &dut.n1_req_wdata_w20, &dut.n1_req_wdata_w21, &dut.n1_req_wdata_w22, &dut.n1_req_wdata_w23, &dut.n1_req_wdata_w24, &dut.n1_req_wdata_w25, &dut.n1_req_wdata_w26, &dut.n1_req_wdata_w27, &dut.n1_req_wdata_w28, &dut.n1_req_wdata_w29, &dut.n1_req_wdata_w30, &dut.n1_req_wdata_w31},
    {&dut.n2_req_wdata_w0, &dut.n2_req_wdata_w1, &dut.n2_req_wdata_w2, &dut.n2_req_wdata_w3, &dut.n2_req_wdata_w4, &dut.n2_req_wdata_w5, &dut.n2_req_wdata_w6, &dut.n2_req_wdata_w7, &dut.n2_req_wdata_w8, &dut.n2_req_wdata_w9, &dut.n2_req_wdata_w10, &dut.n2_req_wdata_w11, &dut.n2_req_wdata_w12, &dut.n2_req_wdata_w13, &dut.n2_req_wdata_w14, &dut.n2_req_wdata_w15, &dut.n2_req_wdata_w16, &dut.n2_req_wdata_w17, &dut.n2_req_wdata_w18, &dut.n2_req_wdata_w19, &dut.n2_req_wdata_w20, &dut.n2_req_wdata_w21, &dut.n2_req_wdata_w22, &dut.n2_req_wdata_w23, &dut.n2_req_wdata_w24, &dut.n2_req_wdata_w25, &dut.n2_req_wdata_w26, &dut.n2_req_wdata_w27, &dut.n2_req_wdata_w28, &dut.n2_req_wdata_w29, &dut.n2_req_wdata_w30, &dut.n2_req_wdata_w31},
    {&dut.n3_req_wdata_w0, &dut.n3_req_wdata_w1, &dut.n3_req_wdata_w2, &dut.n3_req_wdata_w3, &dut.n3_req_wdata_w4, &dut.n3_req_wdata_w5, &dut.n3_req_wdata_w6, &dut.n3_req_wdata_w7, &dut.n3_req_wdata_w8, &dut.n3_req_wdata_w9, &dut.n3_req_wdata_w10, &dut.n3_req_wdata_w11, &dut.n3_req_wdata_w12, &dut.n3_req_wdata_w13, &dut.n3_req_wdata_w14, &dut.n3_req_wdata_w15, &dut.n3_req_wdata_w16, &dut.n3_req_wdata_w17, &dut.n3_req_wdata_w18, &dut.n3_req_wdata_w19, &dut.n3_req_wdata_w20, &dut.n3_req_wdata_w21, &dut.n3_req_wdata_w22, &dut.n3_req_wdata_w23, &dut.n3_req_wdata_w24, &dut.n3_req_wdata_w25, &dut.n3_req_wdata_w26, &dut.n3_req_wdata_w27, &dut.n3_req_wdata_w28, &dut.n3_req_wdata_w29, &dut.n3_req_wdata_w30, &dut.n3_req_wdata_w31},
    {&dut.n4_req_wdata_w0, &dut.n4_req_wdata_w1, &dut.n4_req_wdata_w2, &dut.n4_req_wdata_w3, &dut.n4_req_wdata_w4, &dut.n4_req_wdata_w5, &dut.n4_req_wdata_w6, &dut.n4_req_wdata_w7, &dut.n4_req_wdata_w8, &dut.n4_req_wdata_w9, &dut.n4_req_wdata_w10, &dut.n4_req_wdata_w11, &dut.n4_req_wdata_w12, &dut.n4_req_wdata_w13, &dut.n4_req_wdata_w14, &dut.n4_req_wdata_w15, &dut.n4_req_wdata_w16, &dut.n4_req_wdata_w17, &dut.n4_req_wdata_w18, &dut.n4_req_wdata_w19, &dut.n4_req_wdata_w20, &dut.n4_req_wdata_w21, &dut.n4_req_wdata_w22, &dut.n4_req_wdata_w23, &dut.n4_req_wdata_w24, &dut.n4_req_wdata_w25, &dut.n4_req_wdata_w26, &dut.n4_req_wdata_w27, &dut.n4_req_wdata_w28, &dut.n4_req_wdata_w29, &dut.n4_req_wdata_w30, &dut.n4_req_wdata_w31},
    {&dut.n5_req_wdata_w0, &dut.n5_req_wdata_w1, &dut.n5_req_wdata_w2, &dut.n5_req_wdata_w3, &dut.n5_req_wdata_w4, &dut.n5_req_wdata_w5, &dut.n5_req_wdata_w6, &dut.n5_req_wdata_w7, &dut.n5_req_wdata_w8, &dut.n5_req_wdata_w9, &dut.n5_req_wdata_w10, &dut.n5_req_wdata_w11, &dut.n5_req_wdata_w12, &dut.n5_req_wdata_w13, &dut.n5_req_wdata_w14, &dut.n5_req_wdata_w15, &dut.n5_req_wdata_w16, &dut.n5_req_wdata_w17, &dut.n5_req_wdata_w18, &dut.n5_req_wdata_w19, &dut.n5_req_wdata_w20, &dut.n5_req_wdata_w21, &dut.n5_req_wdata_w22, &dut.n5_req_wdata_w23, &dut.n5_req_wdata_w24, &dut.n5_req_wdata_w25, &dut.n5_req_wdata_w26, &dut.n5_req_wdata_w27, &dut.n5_req_wdata_w28, &dut.n5_req_wdata_w29, &dut.n5_req_wdata_w30, &dut.n5_req_wdata_w31},
    {&dut.n6_req_wdata_w0, &dut.n6_req_wdata_w1, &dut.n6_req_wdata_w2, &dut.n6_req_wdata_w3, &dut.n6_req_wdata_w4, &dut.n6_req_wdata_w5, &dut.n6_req_wdata_w6, &dut.n6_req_wdata_w7, &dut.n6_req_wdata_w8, &dut.n6_req_wdata_w9, &dut.n6_req_wdata_w10, &dut.n6_req_wdata_w11, &dut.n6_req_wdata_w12, &dut.n6_req_wdata_w13, &dut.n6_req_wdata_w14, &dut.n6_req_wdata_w15, &dut.n6_req_wdata_w16, &dut.n6_req_wdata_w17, &dut.n6_req_wdata_w18, &dut.n6_req_wdata_w19, &dut.n6_req_wdata_w20, &dut.n6_req_wdata_w21, &dut.n6_req_wdata_w22, &dut.n6_req_wdata_w23, &dut.n6_req_wdata_w24, &dut.n6_req_wdata_w25, &dut.n6_req_wdata_w26, &dut.n6_req_wdata_w27, &dut.n6_req_wdata_w28, &dut.n6_req_wdata_w29, &dut.n6_req_wdata_w30, &dut.n6_req_wdata_w31},
    {&dut.n7_req_wdata_w0, &dut.n7_req_wdata_w1, &dut.n7_req_wdata_w2, &dut.n7_req_wdata_w3, &dut.n7_req_wdata_w4, &dut.n7_req_wdata_w5, &dut.n7_req_wdata_w6, &dut.n7_req_wdata_w7, &dut.n7_req_wdata_w8, &dut.n7_req_wdata_w9, &dut.n7_req_wdata_w10, &dut.n7_req_wdata_w11, &dut.n7_req_wdata_w12, &dut.n7_req_wdata_w13, &dut.n7_req_wdata_w14, &dut.n7_req_wdata_w15, &dut.n7_req_wdata_w16, &dut.n7_req_wdata_w17, &dut.n7_req_wdata_w18, &dut.n7_req_wdata_w19, &dut.n7_req_wdata_w20, &dut.n7_req_wdata_w21, &dut.n7_req_wdata_w22, &dut.n7_req_wdata_w23, &dut.n7_req_wdata_w24, &dut.n7_req_wdata_w25, &dut.n7_req_wdata_w26, &dut.n7_req_wdata_w27, &dut.n7_req_wdata_w28, &dut.n7_req_wdata_w29, &dut.n7_req_wdata_w30, &dut.n7_req_wdata_w31}
  }};
  io.req_wstrb = {{
    {&dut.n0_req_wstrb_w0, &dut.n0_req_wstrb_w1, &dut.n0_req_wstrb_w2, &dut.n0_req_wstrb_w3, &dut.n0_req_wstrb_w4, &dut.n0_req_wstrb_w5, &dut.n0_req_wstrb_w6, &dut.n0_req_wstrb_w7, &dut.n0_req_wstrb_w8, &dut.n0_req_wstrb_w9, &dut.n0_req_wstrb_w10, &dut.n0_req_wstrb_w11, &dut.n0_req_wstrb_w12, &dut.n0_req_wstrb_w13, &dut.n0_req_wstrb_w14, &dut.n0_req_wstrb_w15, &dut.n0_req_wstrb_w16, &dut.n0_req_wstrb_w17, &dut.n0_req_wstrb_w18, &dut.n0_req_wstrb_w19, &dut.n0_req_wstrb_w20, &dut.n0_req_wstrb_w21, &dut.n0_req_wstrb_w22, &dut.n0_req_wstrb_w23, &dut.n0_req_wstrb_w24, &dut.n0_req_wstrb_w25, &dut.n0_req_wstrb_w26, &dut.n0_req_wstrb_w27, &dut.n0_req_wstrb_w28, &dut.n0_req_wstrb_w29, &dut.n0_req_wstrb_w30, &dut.n0_req_wstrb_w31},
    {&dut.n1_req_wstrb_w0, &dut.n1_req_wstrb_w1, &dut.n1_req_wstrb_w2, &dut.n1_req_wstrb_w3, &dut.n1_req_wstrb_w4, &dut.n1_req_wstrb_w5, &dut.n1_req_wstrb_w6, &dut.n1_req_wstrb_w7, &dut.n1_req_wstrb_w8, &dut.n1_req_wstrb_w9, &dut.n1_req_wstrb_w10, &dut.n1_req_wstrb_w11, &dut.n1_req_wstrb_w12, &dut.n1_req_wstrb_w13, &dut.n1_req_wstrb_w14, &dut.n1_req_wstrb_w15, &dut.n1_req_wstrb_w16, &dut.n1_req_wstrb_w17, &dut.n1_req_wstrb_w18, &dut.n1_req_wstrb_w19, &dut.n1_req_wstrb_w20, &dut.n1_req_wstrb_w21, &dut.n1_req_wstrb_w22, &dut.n1_req_wstrb_w23, &dut.n1_req_wstrb_w24, &dut.n1_req_wstrb_w25, &dut.n1_req_wstrb_w26, &dut.n1_req_wstrb_w27, &dut.n1_req_wstrb_w28, &dut.n1_req_wstrb_w29, &dut.n1_req_wstrb_w30, &dut.n1_req_wstrb_w31},
    {&dut.n2_req_wstrb_w0, &dut.n2_req_wstrb_w1, &dut.n2_req_wstrb_w2, &dut.n2_req_wstrb_w3, &dut.n2_req_wstrb_w4, &dut.n2_req_wstrb_w5, &dut.n2_req_wstrb_w6, &dut.n2_req_wstrb_w7, &dut.n2_req_wstrb_w8, &dut.n2_req_wstrb_w9, &dut.n2_req_wstrb_w10, &dut.n2_req_wstrb_w11, &dut.n2_req_wstrb_w12, &dut.n2_req_wstrb_w13, &dut.n2_req_wstrb_w14, &dut.n2_req_wstrb_w15, &dut.n2_req_wstrb_w16, &dut.n2_req_wstrb_w17, &dut.n2_req_wstrb_w18, &dut.n2_req_wstrb_w19, &dut.n2_req_wstrb_w20, &dut.n2_req_wstrb_w21, &dut.n2_req_wstrb_w22, &dut.n2_req_wstrb_w23, &dut.n2_req_wstrb_w24, &dut.n2_req_wstrb_w25, &dut.n2_req_wstrb_w26, &dut.n2_req_wstrb_w27, &dut.n2_req_wstrb_w28, &dut.n2_req_wstrb_w29, &dut.n2_req_wstrb_w30, &dut.n2_req_wstrb_w31},
    {&dut.n3_req_wstrb_w0, &dut.n3_req_wstrb_w1, &dut.n3_req_wstrb_w2, &dut.n3_req_wstrb_w3, &dut.n3_req_wstrb_w4, &dut.n3_req_wstrb_w5, &dut.n3_req_wstrb_w6, &dut.n3_req_wstrb_w7, &dut.n3_req_wstrb_w8, &dut.n3_req_wstrb_w9, &dut.n3_req_wstrb_w10, &dut.n3_req_wstrb_w11, &dut.n3_req_wstrb_w12, &dut.n3_req_wstrb_w13, &dut.n3_req_wstrb_w14, &dut.n3_req_wstrb_w15, &dut.n3_req_wstrb_w16, &dut.n3_req_wstrb_w17, &dut.n3_req_wstrb_w18, &dut.n3_req_wstrb_w19, &dut.n3_req_wstrb_w20, &dut.n3_req_wstrb_w21, &dut.n3_req_wstrb_w22, &dut.n3_req_wstrb_w23, &dut.n3_req_wstrb_w24, &dut.n3_req_wstrb_w25, &dut.n3_req_wstrb_w26, &dut.n3_req_wstrb_w27, &dut.n3_req_wstrb_w28, &dut.n3_req_wstrb_w29, &dut.n3_req_wstrb_w30, &dut.n3_req_wstrb_w31},
    {&dut.n4_req_wstrb_w0, &dut.n4_req_wstrb_w1, &dut.n4_req_wstrb_w2, &dut.n4_req_wstrb_w3, &dut.n4_req_wstrb_w4, &dut.n4_req_wstrb_w5, &dut.n4_req_wstrb_w6, &dut.n4_req_wstrb_w7, &dut.n4_req_wstrb_w8, &dut.n4_req_wstrb_w9, &dut.n4_req_wstrb_w10, &dut.n4_req_wstrb_w11, &dut.n4_req_wstrb_w12, &dut.n4_req_wstrb_w13, &dut.n4_req_wstrb_w14, &dut.n4_req_wstrb_w15, &dut.n4_req_wstrb_w16, &dut.n4_req_wstrb_w17, &dut.n4_req_wstrb_w18, &dut.n4_req_wstrb_w19, &dut.n4_req_wstrb_w20, &dut.n4_req_wstrb_w21, &dut.n4_req_wstrb_w22, &dut.n4_req_wstrb_w23, &dut.n4_req_wstrb_w24, &dut.n4_req_wstrb_w25, &dut.n4_req_wstrb_w26, &dut.n4_req_wstrb_w27, &dut.n4_req_wstrb_w28, &dut.n4_req_wstrb_w29, &dut.n4_req_wstrb_w30, &dut.n4_req_wstrb_w31},
    {&dut.n5_req_wstrb_w0, &dut.n5_req_wstrb_w1, &dut.n5_req_wstrb_w2, &dut.n5_req_wstrb_w3, &dut.n5_req_wstrb_w4, &dut.n5_req_wstrb_w5, &dut.n5_req_wstrb_w6, &dut.n5_req_wstrb_w7, &dut.n5_req_wstrb_w8, &dut.n5_req_wstrb_w9, &dut.n5_req_wstrb_w10, &dut.n5_req_wstrb_w11, &dut.n5_req_wstrb_w12, &dut.n5_req_wstrb_w13, &dut.n5_req_wstrb_w14, &dut.n5_req_wstrb_w15, &dut.n5_req_wstrb_w16, &dut.n5_req_wstrb_w17, &dut.n5_req_wstrb_w18, &dut.n5_req_wstrb_w19, &dut.n5_req_wstrb_w20, &dut.n5_req_wstrb_w21, &dut.n5_req_wstrb_w22, &dut.n5_req_wstrb_w23, &dut.n5_req_wstrb_w24, &dut.n5_req_wstrb_w25, &dut.n5_req_wstrb_w26, &dut.n5_req_wstrb_w27, &dut.n5_req_wstrb_w28, &dut.n5_req_wstrb_w29, &dut.n5_req_wstrb_w30, &dut.n5_req_wstrb_w31},
    {&dut.n6_req_wstrb_w0, &dut.n6_req_wstrb_w1, &dut.n6_req_wstrb_w2, &dut.n6_req_wstrb_w3, &dut.n6_req_wstrb_w4, &dut.n6_req_wstrb_w5, &dut.n6_req_wstrb_w6, &dut.n6_req_wstrb_w7, &dut.n6_req_wstrb_w8, &dut.n6_req_wstrb_w9, &dut.n6_req_wstrb_w10, &dut.n6_req_wstrb_w11, &dut.n6_req_wstrb_w12, &dut.n6_req_wstrb_w13, &dut.n6_req_wstrb_w14, &dut.n6_req_wstrb_w15, &dut.n6_req_wstrb_w16, &dut.n6_req_wstrb_w17, &dut.n6_req_wstrb_w18, &dut.n6_req_wstrb_w19, &dut.n6_req_wstrb_w20, &dut.n6_req_wstrb_w21, &dut.n6_req_wstrb_w22, &dut.n6_req_wstrb_w23, &dut.n6_req_wstrb_w24, &dut.n6_req_wstrb_w25, &dut.n6_req_wstrb_w26, &dut.n6_req_wstrb_w27, &dut.n6_req_wstrb_w28, &dut.n6_req_wstrb_w29, &dut.n6_req_wstrb_w30, &dut.n6_req_wstrb_w31},
    {&dut.n7_req_wstrb_w0, &dut.n7_req_wstrb_w1, &dut.n7_req_wstrb_w2, &dut.n7_req_wstrb_w3, &dut.n7_req_wstrb_w4, &dut.n7_req_wstrb_w5, &dut.n7_req_wstrb_w6, &dut.n7_req_wstrb_w7, &dut.n7_req_wstrb_w8, &dut.n7_req_wstrb_w9, &dut.n7_req_wstrb_w10, &dut.n7_req_wstrb_w11, &dut.n7_req_wstrb_w12, &dut.n7_req_wstrb_w13, &dut.n7_req_wstrb_w14, &dut.n7_req_wstrb_w15, &dut.n7_req_wstrb_w16, &dut.n7_req_wstrb_w17, &dut.n7_req_wstrb_w18, &dut.n7_req_wstrb_w19, &dut.n7_req_wstrb_w20, &dut.n7_req_wstrb_w21, &dut.n7_req_wstrb_w22, &dut.n7_req_wstrb_w23, &dut.n7_req_wstrb_w24, &dut.n7_req_wstrb_w25, &dut.n7_req_wstrb_w26, &dut.n7_req_wstrb_w27, &dut.n7_req_wstrb_w28, &dut.n7_req_wstrb_w29, &dut.n7_req_wstrb_w30, &dut.n7_req_wstrb_w31}
  }};
  io.req_tag = {&dut.n0_req_tag, &dut.n1_req_tag, &dut.n2_req_tag, &dut.n3_req_tag,
                &dut.n4_req_tag, &dut.n5_req_tag, &dut.n6_req_tag, &dut.n7_req_tag};

  io.rsp_valid = {&dut.n0_rsp_valid, &dut.n1_rsp_valid, &dut.n2_rsp_valid, &dut.n3_rsp_valid,
                  &dut.n4_rsp_valid, &dut.n5_rsp_valid, &dut.n6_rsp_valid, &dut.n7_rsp_valid};
  io.rsp_ready = {&dut.n0_rsp_ready, &dut.n1_rsp_ready, &dut.n2_rsp_ready, &dut.n3_rsp_ready,
                  &dut.n4_rsp_ready, &dut.n5_rsp_ready, &dut.n6_rsp_ready, &dut.n7_rsp_ready};
  io.rsp_rdata = {{
    {&dut.n0_rsp_rdata_w0, &dut.n0_rsp_rdata_w1, &dut.n0_rsp_rdata_w2, &dut.n0_rsp_rdata_w3, &dut.n0_rsp_rdata_w4, &dut.n0_rsp_rdata_w5, &dut.n0_rsp_rdata_w6, &dut.n0_rsp_rdata_w7, &dut.n0_rsp_rdata_w8, &dut.n0_rsp_rdata_w9, &dut.n0_rsp_rdata_w10, &dut.n0_rsp_rdata_w11, &dut.n0_rsp_rdata_w12, &dut.n0_rsp_rdata_w13, &dut.n0_rsp_rdata_w14, &dut.n0_rsp_rdata_w15, &dut.n0_rsp_rdata_w16, &dut.n0_rsp_rdata_w17, &dut.n0_rsp_rdata_w18, &dut.n0_rsp_rdata_w19, &dut.n0_rsp_rdata_w20, &dut.n0_rsp_rdata_w21, &dut.n0_rsp_rdata_w22, &dut.n0_rsp_rdata_w23, &dut.n0_rsp_rdata_w24, &dut.n0_rsp_rdata_w25, &dut.n0_rsp_rdata_w26, &dut.n0_rsp_rdata_w27, &dut.n0_rsp_rdata_w28, &dut.n0_rsp_rdata_w29, &dut.n0_rsp_rdata_w30, &dut.n0_rsp_rdata_w31},
    {&dut.n1_rsp_rdata_w0, &dut.n1_rsp_rdata_w1, &dut.n1_rsp_rdata_w2, &dut.n1_rsp_rdata_w3, &dut.n1_rsp_rdata_w4, &dut.n1_rsp_rdata_w5, &dut.n1_rsp_rdata_w6, &dut.n1_rsp_rdata_w7, &dut.n1_rsp_rdata_w8, &dut.n1_rsp_rdata_w9, &dut.n1_rsp_rdata_w10, &dut.n1_rsp_rdata_w11, &dut.n1_rsp_rdata_w12, &dut.n1_rsp_rdata_w13, &dut.n1_rsp_rdata_w14, &dut.n1_rsp_rdata_w15, &dut.n1_rsp_rdata_w16, &dut.n1_rsp_rdata_w17, &dut.n1_rsp_rdata_w18, &dut.n1_rsp_rdata_w19, &dut.n1_rsp_rdata_w20, &dut.n1_rsp_rdata_w21, &dut.n1_rsp_rdata_w22, &dut.n1_rsp_rdata_w23, &dut.n1_rsp_rdata_w24, &dut.n1_rsp_rdata_w25, &dut.n1_rsp_rdata_w26, &dut.n1_rsp_rdata_w27, &dut.n1_rsp_rdata_w28, &dut.n1_rsp_rdata_w29, &dut.n1_rsp_rdata_w30, &dut.n1_rsp_rdata_w31},
    {&dut.n2_rsp_rdata_w0, &dut.n2_rsp_rdata_w1, &dut.n2_rsp_rdata_w2, &dut.n2_rsp_rdata_w3, &dut.n2_rsp_rdata_w4, &dut.n2_rsp_rdata_w5, &dut.n2_rsp_rdata_w6, &dut.n2_rsp_rdata_w7, &dut.n2_rsp_rdata_w8, &dut.n2_rsp_rdata_w9, &dut.n2_rsp_rdata_w10, &dut.n2_rsp_rdata_w11, &dut.n2_rsp_rdata_w12, &dut.n2_rsp_rdata_w13, &dut.n2_rsp_rdata_w14, &dut.n2_rsp_rdata_w15, &dut.n2_rsp_rdata_w16, &dut.n2_rsp_rdata_w17, &dut.n2_rsp_rdata_w18, &dut.n2_rsp_rdata_w19, &dut.n2_rsp_rdata_w20, &dut.n2_rsp_rdata_w21, &dut.n2_rsp_rdata_w22, &dut.n2_rsp_rdata_w23, &dut.n2_rsp_rdata_w24, &dut.n2_rsp_rdata_w25, &dut.n2_rsp_rdata_w26, &dut.n2_rsp_rdata_w27, &dut.n2_rsp_rdata_w28, &dut.n2_rsp_rdata_w29, &dut.n2_rsp_rdata_w30, &dut.n2_rsp_rdata_w31},
    {&dut.n3_rsp_rdata_w0, &dut.n3_rsp_rdata_w1, &dut.n3_rsp_rdata_w2, &dut.n3_rsp_rdata_w3, &dut.n3_rsp_rdata_w4, &dut.n3_rsp_rdata_w5, &dut.n3_rsp_rdata_w6, &dut.n3_rsp_rdata_w7, &dut.n3_rsp_rdata_w8, &dut.n3_rsp_rdata_w9, &dut.n3_rsp_rdata_w10, &dut.n3_rsp_rdata_w11, &dut.n3_rsp_rdata_w12, &dut.n3_rsp_rdata_w13, &dut.n3_rsp_rdata_w14, &dut.n3_rsp_rdata_w15, &dut.n3_rsp_rdata_w16, &dut.n3_rsp_rdata_w17, &dut.n3_rsp_rdata_w18, &dut.n3_rsp_rdata_w19, &dut.n3_rsp_rdata_w20, &dut.n3_rsp_rdata_w21, &dut.n3_rsp_rdata_w22, &dut.n3_rsp_rdata_w23, &dut.n3_rsp_rdata_w24, &dut.n3_rsp_rdata_w25, &dut.n3_rsp_rdata_w26, &dut.n3_rsp_rdata_w27, &dut.n3_rsp_rdata_w28, &dut.n3_rsp_rdata_w29, &dut.n3_rsp_rdata_w30, &dut.n3_rsp_rdata_w31},
    {&dut.n4_rsp_rdata_w0, &dut.n4_rsp_rdata_w1, &dut.n4_rsp_rdata_w2, &dut.n4_rsp_rdata_w3, &dut.n4_rsp_rdata_w4, &dut.n4_rsp_rdata_w5, &dut.n4_rsp_rdata_w6, &dut.n4_rsp_rdata_w7, &dut.n4_rsp_rdata_w8, &dut.n4_rsp_rdata_w9, &dut.n4_rsp_rdata_w10, &dut.n4_rsp_rdata_w11, &dut.n4_rsp_rdata_w12, &dut.n4_rsp_rdata_w13, &dut.n4_rsp_rdata_w14, &dut.n4_rsp_rdata_w15, &dut.n4_rsp_rdata_w16, &dut.n4_rsp_rdata_w17, &dut.n4_rsp_rdata_w18, &dut.n4_rsp_rdata_w19, &dut.n4_rsp_rdata_w20, &dut.n4_rsp_rdata_w21, &dut.n4_rsp_rdata_w22, &dut.n4_rsp_rdata_w23, &dut.n4_rsp_rdata_w24, &dut.n4_rsp_rdata_w25, &dut.n4_rsp_rdata_w26, &dut.n4_rsp_rdata_w27, &dut.n4_rsp_rdata_w28, &dut.n4_rsp_rdata_w29, &dut.n4_rsp_rdata_w30, &dut.n4_rsp_rdata_w31},
    {&dut.n5_rsp_rdata_w0, &dut.n5_rsp_rdata_w1, &dut.n5_rsp_rdata_w2, &dut.n5_rsp_rdata_w3, &dut.n5_rsp_rdata_w4, &dut.n5_rsp_rdata_w5, &dut.n5_rsp_rdata_w6, &dut.n5_rsp_rdata_w7, &dut.n5_rsp_rdata_w8, &dut.n5_rsp_rdata_w9, &dut.n5_rsp_rdata_w10, &dut.n5_rsp_rdata_w11, &dut.n5_rsp_rdata_w12, &dut.n5_rsp_rdata_w13, &dut.n5_rsp_rdata_w14, &dut.n5_rsp_rdata_w15, &dut.n5_rsp_rdata_w16, &dut.n5_rsp_rdata_w17, &dut.n5_rsp_rdata_w18, &dut.n5_rsp_rdata_w19, &dut.n5_rsp_rdata_w20, &dut.n5_rsp_rdata_w21, &dut.n5_rsp_rdata_w22, &dut.n5_rsp_rdata_w23, &dut.n5_rsp_rdata_w24, &dut.n5_rsp_rdata_w25, &dut.n5_rsp_rdata_w26, &dut.n5_rsp_rdata_w27, &dut.n5_rsp_rdata_w28, &dut.n5_rsp_rdata_w29, &dut.n5_rsp_rdata_w30, &dut.n5_rsp_rdata_w31},
    {&dut.n6_rsp_rdata_w0, &dut.n6_rsp_rdata_w1, &dut.n6_rsp_rdata_w2, &dut.n6_rsp_rdata_w3, &dut.n6_rsp_rdata_w4, &dut.n6_rsp_rdata_w5, &dut.n6_rsp_rdata_w6, &dut.n6_rsp_rdata_w7, &dut.n6_rsp_rdata_w8, &dut.n6_rsp_rdata_w9, &dut.n6_rsp_rdata_w10, &dut.n6_rsp_rdata_w11, &dut.n6_rsp_rdata_w12, &dut.n6_rsp_rdata_w13, &dut.n6_rsp_rdata_w14, &dut.n6_rsp_rdata_w15, &dut.n6_rsp_rdata_w16, &dut.n6_rsp_rdata_w17, &dut.n6_rsp_rdata_w18, &dut.n6_rsp_rdata_w19, &dut.n6_rsp_rdata_w20, &dut.n6_rsp_rdata_w21, &dut.n6_rsp_rdata_w22, &dut.n6_rsp_rdata_w23, &dut.n6_rsp_rdata_w24, &dut.n6_rsp_rdata_w25, &dut.n6_rsp_rdata_w26, &dut.n6_rsp_rdata_w27, &dut.n6_rsp_rdata_w28, &dut.n6_rsp_rdata_w29, &dut.n6_rsp_rdata_w30, &dut.n6_rsp_rdata_w31},
    {&dut.n7_rsp_rdata_w0, &dut.n7_rsp_rdata_w1, &dut.n7_rsp_rdata_w2, &dut.n7_rsp_rdata_w3, &dut.n7_rsp_rdata_w4, &dut.n7_rsp_rdata_w5, &dut.n7_rsp_rdata_w6, &dut.n7_rsp_rdata_w7, &dut.n7_rsp_rdata_w8, &dut.n7_rsp_rdata_w9, &dut.n7_rsp_rdata_w10, &dut.n7_rsp_rdata_w11, &dut.n7_rsp_rdata_w12, &dut.n7_rsp_rdata_w13, &dut.n7_rsp_rdata_w14, &dut.n7_rsp_rdata_w15, &dut.n7_rsp_rdata_w16, &dut.n7_rsp_rdata_w17, &dut.n7_rsp_rdata_w18, &dut.n7_rsp_rdata_w19, &dut.n7_rsp_rdata_w20, &dut.n7_rsp_rdata_w21, &dut.n7_rsp_rdata_w22, &dut.n7_rsp_rdata_w23, &dut.n7_rsp_rdata_w24, &dut.n7_rsp_rdata_w25, &dut.n7_rsp_rdata_w26, &dut.n7_rsp_rdata_w27, &dut.n7_rsp_rdata_w28, &dut.n7_rsp_rdata_w29, &dut.n7_rsp_rdata_w30, &dut.n7_rsp_rdata_w31}
  }};
  io.rsp_tag = {&dut.n0_rsp_tag, &dut.n1_rsp_tag, &dut.n2_rsp_tag, &dut.n3_rsp_tag,
                &dut.n4_rsp_tag, &dut.n5_rsp_tag, &dut.n6_rsp_tag, &dut.n7_rsp_tag};
  return io;
}

static DataWords make_data(std::uint64_t base) {
  DataWords out{};
  for (int i = 0; i < kWords; i++)
    out[i] = base + static_cast<std::uint64_t>(i);
  return out;
}

static bool equal_data(const std::array<W64 *, kWords> &got, const DataWords &exp) {
  for (int i = 0; i < kWords; i++) {
    if (got[i]->value() != exp[i])
      return false;
  }
  return true;
}

static int hop_distance(int src, int dest) {
  const int ring[8] = {0, 1, 3, 5, 7, 6, 4, 2};
  int pos[8] = {0};
  for (int i = 0; i < 8; i++)
    pos[ring[i]] = i;
  int cw = (pos[dest] - pos[src] + 8) % 8;
  int cc = (pos[src] - pos[dest] + 8) % 8;
  return (cw < cc) ? cw : cc;
}

static std::uint64_t send_req(Testbench<pyc::gen::janus_tmu_pyc> &tb, Ifaces &io, int node, bool is_write, std::uint32_t addr,
                              const DataWords &data, std::uint64_t &cycle) {
  *io.req_valid[node] = W1(1);
  *io.req_write[node] = W1(is_write ? 1u : 0u);
  *io.req_addr[node] = W20(addr);
  for (int w = 0; w < kWords; w++) {
    *io.req_wdata[node][w] = W64(data[w]);
    *io.req_wstrb[node][w] = W8(0xFF);
  }
  *io.req_tag[node] = W20(addr);

  if (!io.req_ready[node]->toBool()) {
    std::cerr << "FAIL: req_ready low at issue (node=" << node << ")\n";
    std::exit(1);
  }

  std::uint64_t t_issue = cycle;
  tb.runCycles(1);
  cycle++;
  *io.req_valid[node] = W1(0);
  return t_issue;
}

static std::uint64_t wait_rsp(Testbench<pyc::gen::janus_tmu_pyc> &tb, Ifaces &io, int node, std::uint32_t addr, std::uint64_t &cycle,
                              std::uint64_t max_cycles) {
  for (std::uint64_t i = 0; i < max_cycles; i++) {
    if (io.rsp_valid[node]->toBool() && io.rsp_tag[node]->value() == addr) {
      return cycle;
    }
    tb.runCycles(1);
    cycle++;
  }
  std::cerr << "FAIL: timeout waiting for response (node=" << node << ")\n";
  std::exit(1);
}

} // namespace

int main() {
  pyc::gen::janus_tmu_pyc dut{};
  Testbench<pyc::gen::janus_tmu_pyc> tb(dut);
  tb.addClock(dut.clk, /*halfPeriodSteps=*/1);

  auto io = make_ifaces(dut);

  // Default all inputs.
  for (int i = 0; i < kNodes; i++) {
    *io.req_valid[i] = W1(0);
    *io.req_write[i] = W1(0);
    *io.req_addr[i] = W20(0);
    for (int w = 0; w < kWords; w++) {
      *io.req_wdata[i][w] = W64(0);
      *io.req_wstrb[i][w] = W8(0);
    }
    *io.req_tag[i] = W20(0);
    *io.rsp_ready[i] = W1(1);
  }

  tb.reset(dut.rst, /*cyclesAsserted=*/2, /*cyclesDeasserted=*/1);
  std::uint64_t cycle = 0;

  auto addr_for = [](int pipe, int idx) -> std::uint32_t {
    return static_cast<std::uint32_t>((idx << 11) | (pipe << 8));
  };

  // Test 1: local access node2 -> pipe2 (hop 0, latency 4)
  {
    int node = 2;
    int pipe = 2;
    DataWords data = make_data(0x1000);
    std::uint32_t addr = addr_for(pipe, 0);

    auto t_issue = send_req(tb, io, node, /*write=*/true, addr, data, cycle);
    auto t_rsp = wait_rsp(tb, io, node, addr, cycle, 100);
    int hop = hop_distance(node, pipe);
    std::uint64_t expect = 4 + 2 * hop;
    if (t_rsp - t_issue != expect) {
      std::cerr << "FAIL: local write latency got=" << (t_rsp - t_issue) << " expect=" << expect << "\n";
      return 1;
    }

    addr = addr_for(pipe, 0);
    t_issue = send_req(tb, io, node, /*write=*/false, addr, data, cycle);
    t_rsp = wait_rsp(tb, io, node, addr, cycle, 100);
    if (t_rsp - t_issue != expect) {
      std::cerr << "FAIL: local read latency got=" << (t_rsp - t_issue) << " expect=" << expect << "\n";
      return 1;
    }
    if (!equal_data(io.rsp_rdata[node], data)) {
      std::cerr << "FAIL: local read data mismatch\n";
      return 1;
    }
  }

  // Test 2: cw shortest path node0 -> pipe1 (hop 1, latency 6)
  {
    int node = 0;
    int pipe = 1;
    DataWords data = make_data(0x2000);
    std::uint32_t addr = addr_for(pipe, 1);

    auto t_issue = send_req(tb, io, node, /*write=*/true, addr, data, cycle);
    auto t_rsp = wait_rsp(tb, io, node, addr, cycle, 200);
    int hop = hop_distance(node, pipe);
    std::uint64_t expect = 4 + 2 * hop;
    if (t_rsp - t_issue != expect) {
      std::cerr << "FAIL: cw write latency got=" << (t_rsp - t_issue) << " expect=" << expect << "\n";
      return 1;
    }

    addr = addr_for(pipe, 1);
    t_issue = send_req(tb, io, node, /*write=*/false, addr, data, cycle);
    t_rsp = wait_rsp(tb, io, node, addr, cycle, 200);
    if (t_rsp - t_issue != expect) {
      std::cerr << "FAIL: cw read latency got=" << (t_rsp - t_issue) << " expect=" << expect << "\n";
      return 1;
    }
    if (!equal_data(io.rsp_rdata[node], data)) {
      std::cerr << "FAIL: cw read data mismatch\n";
      return 1;
    }
  }

  // Test 3: cc shortest path node0 -> pipe2 (hop 1, latency 6)
  {
    int node = 0;
    int pipe = 2;
    DataWords data = make_data(0x3000);
    std::uint32_t addr = addr_for(pipe, 2);

    auto t_issue = send_req(tb, io, node, /*write=*/true, addr, data, cycle);
    auto t_rsp = wait_rsp(tb, io, node, addr, cycle, 200);
    int hop = hop_distance(node, pipe);
    std::uint64_t expect = 4 + 2 * hop;
    if (t_rsp - t_issue != expect) {
      std::cerr << "FAIL: cc write latency got=" << (t_rsp - t_issue) << " expect=" << expect << "\n";
      return 1;
    }

    addr = addr_for(pipe, 2);
    t_issue = send_req(tb, io, node, /*write=*/false, addr, data, cycle);
    t_rsp = wait_rsp(tb, io, node, addr, cycle, 200);
    if (t_rsp - t_issue != expect) {
      std::cerr << "FAIL: cc read latency got=" << (t_rsp - t_issue) << " expect=" << expect << "\n";
      return 1;
    }
    if (!equal_data(io.rsp_rdata[node], data)) {
      std::cerr << "FAIL: cc read data mismatch\n";
      return 1;
    }
  }

  std::cout << "ok: janus_tmu_pyc tests passed\n";
  return 0;
}
